---
title: "STA6349: Distribution Theory"
author: "Your Name Here"
execute:
  echo: true
  warning: false
  message: false
  error: true
format: 
  html:
    embed-resources: true
editor: source
---

**1. Suppose that the amount of product used in one day, represented by $Y$, has a gamma distribution with $\alpha=1.5$ and $\beta=3.0$.**

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution?**

**c. What is the variance of the distribution?**

**d. What is the probability that an earthquake striking the regions will be a minor earthquake (note: the earthquake will fall between 2.0 and 3.0 on the Richter scale)?**

**e. What is the probability that an earthquake striking the regions will be a strong earthquake (note: minimum value is a 6.0 on the Richter scale) or worse?**

**2. A parking lot has two entrances. Cars arrive at Entrance A at an average of 3 cars per hour and at Entrance B at an average of 4 cars per hour. We assume that the number of cars arriving at the two entrances are independent. Let $Y$ be the number of cars arriving to the parking lot in a given hour. **

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution?**

**c. What is the variance of the distribution?**

**d. What is the probability that a total of 3 cars will arrive at the parking lot in a given hour?**

**e. What is the probability that 10 or more cars arrive at the parking lot in a given hour?**

**3. During an 8 hour shift, the proportion of time that, $Y$, a sheet-metal stamping machine is down for maintenance or repairs has a beta distribution with $\alpha=1$ and $\beta=2$. Note that we are also interested in the cost (in hundreds of dollars) of downtime, due to lost production and cost of maintenance and repair, given by $C=10+20Y+4Y^2$**

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution $f(y)$?**

**c. What is the variance of the distribution $f(y)$?**

**d. Find the probability distribution for $C$?**

**e. What is the mean of the distribution $f(c)$?**

**f. What is the variance of the distribution $f(c)$?**

**g. What is the probability that the cost is less than $2000? (Note! Remember that $C$ is discussed in hundreds of dollars.)**



**4. The cycle time for trucks hauling concrete to a highway construction site is consistently between 50 and 70 minutes, with equal probability of any time. Let $Y$ be the cycle time.**

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution?**

**c. What is the variance of the distribution?**

**d. What is the probability that the cycle time is lower than 55 minutes?**

**e. What is the probability that the cycle time is between 55 and 60 minutes?**



**5. A fire-detection device utilizes three temperature sensitive cells acting independently of each other in a manner that any one or more may activate the alarm. Each cell possesses a probability of $p = 0.80$ of activating the alarm when the temperature reaches 100&deg;C or more. Let $Y$ equal the number of cells activating the alarm when the temperature reaches 100&deg;C.**

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution?**

**c. What is the variance of the distribution?**

**d. Find the probability that the alarm will function when the temperature reaches 100&deg;C.**



**6. Scores on an examination are assumed to be normally distributed with mean 75 and variance 36. Let $Y$ equal the exam score.**

**a. Find the probability distribution for $Y$.**

**b. What is the mean of the distribution?**

**c. What is the variance of the distribution?**

**d. What is the probability that a person taking the examination passes with at least a C- (note: minimum value for C- is 70%)?**

**e. What is the probability that a person taking the examination scores above an A or A- (note: minimum value for A- is 90%)**

**f. Suppose the students scoring in the 10% of this distribution are to receive an A grade. What is the minimum score a student must achieve to earn an A grade?**